// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXGiemIauzUxlC4u5Tdkc1h5uAf4McSI',
    appId: '1:988746847535:web:185b30c02c414538c5bdda',
    messagingSenderId: '988746847535',
    projectId: 'keep-it-clean-project-123',
    authDomain: 'keep-it-clean-project-123.firebaseapp.com',
    storageBucket: 'keep-it-clean-project-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgogfi7ZF44XITV9qxvnkjwtvtaH_hDg',
    appId: '1:988746847535:android:5829bb1d644c3b81c5bdda',
    messagingSenderId: '988746847535',
    projectId: 'keep-it-clean-project-123',
    storageBucket: 'keep-it-clean-project-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTJXsMJB5mUGQNwofGIdLjvsQle5s5A2w',
    appId: '1:988746847535:ios:65d4a935c69602bfc5bdda',
    messagingSenderId: '988746847535',
    projectId: 'keep-it-clean-project-123',
    storageBucket: 'keep-it-clean-project-123.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTJXsMJB5mUGQNwofGIdLjvsQle5s5A2w',
    appId: '1:988746847535:ios:65d4a935c69602bfc5bdda',
    messagingSenderId: '988746847535',
    projectId: 'keep-it-clean-project-123',
    storageBucket: 'keep-it-clean-project-123.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvXGiemIauzUxlC4u5Tdkc1h5uAf4McSI',
    appId: '1:988746847535:web:df05c26d065c4137c5bdda',
    messagingSenderId: '988746847535',
    projectId: 'keep-it-clean-project-123',
    authDomain: 'keep-it-clean-project-123.firebaseapp.com',
    storageBucket: 'keep-it-clean-project-123.firebasestorage.app',
  );
}
